# Prometheus ServiceMonitor for Order Service
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: order-service-monitor
  namespace: mambogo-prod
  labels:
    app: order-service
    tier: backend
spec:
  selector:
    matchLabels:
      app: order-service
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 30s
    scrapeTimeout: 10s

---
# Prometheus ServiceMonitor for Payment Service
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: payment-service-monitor
  namespace: mambogo-prod
  labels:
    app: payment-service
    tier: backend
spec:
  selector:
    matchLabels:
      app: payment-service
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 30s
    scrapeTimeout: 10s

---
# Prometheus ServiceMonitor for Product Service
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: product-service-monitor
  namespace: mambogo-prod
  labels:
    app: product-service
    tier: backend
spec:
  selector:
    matchLabels:
      app: product-service
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 30s
    scrapeTimeout: 10s

---
# Prometheus ServiceMonitor for Cart Service
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cart-service-monitor
  namespace: mambogo-prod
  labels:
    app: cart-service
    tier: backend
spec:
  selector:
    matchLabels:
      app: cart-service
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 30s
    scrapeTimeout: 10s

---
# Prometheus ServiceMonitor for Gateway Service
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gateway-service-monitor
  namespace: mambogo-prod
  labels:
    app: gateway-service
    tier: frontend
spec:
  selector:
    matchLabels:
      app: gateway-service
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 30s
    scrapeTimeout: 10s
