spring:
  application.name: gateway-service
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: ${PRODUCT_URL:http://localhost:8082}
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=1
        - id: cart-service
          uri: ${CART_URL:http://localhost:8083}
          predicates:
            - Path=/api/cart/**
          filters:
            - StripPrefix=1
        - id: order-service
          uri: ${ORDER_URL:http://localhost:8084}
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=1
        - id: payment-service
          uri: ${PAYMENT_URL:http://localhost:8085}
          predicates:
            - Path=/api/payments/**
          filters:
            - StripPrefix=1

server.port: 8080

spring.security.oauth2.resourceserver.jwt.issuer-uri: ${KC_ISSUER:http://localhost:8081/realms/ecommerce}

management:
  endpoints.web.exposure.include: health,info,prometheus
  tracing.sampling.probability: 1.0
management.zipkin.tracing.endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}
