# Docker Compose Environment Configuration
PRODUCT_URL: http://product-service:8082
CART_URL: http://cart-service:8083
ORDER_URL: http://order-service:8084
PAYMENT_URL: http://payment-service:8085
KC_ISSUER: http://keycloak:8080/realms/ecommerce
ZIPKIN_ENDPOINT: http://zipkin:9411/api/v2/spans

# CORS Configuration for Docker Compose (Demo Environment)
mambogo:
  cors:
    enabled: true
    allowed-origins:
      - "https://demo.mambogo.com"
      - "http://localhost:5173"  # For local development against Docker backend
    allowed-methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
      - "PATCH"
    allowed-headers:
      - "Authorization"
      - "Content-Type"
      - "Accept"
      - "Origin"
      - "Access-Control-Request-Method"
      - "Access-Control-Request-Headers"
      - "X-Idempotency-Key"
      - "X-Correlation-ID"
    exposed-headers:
      - "Access-Control-Allow-Origin"
      - "Access-Control-Allow-Credentials"
      - "X-Correlation-ID"
      - "X-Rate-Limit-Remaining"
      - "X-Rate-Limit-Retry-After-Seconds"
    allow-credentials: true
    max-age: 3600
    # Advanced CORS Policy Configuration for Demo Environment
    policy:
      enforcement-enabled: true
      auto-block-enabled: true
      auto-block-threshold: 15
      require-user-agent: true
      max-requests-per-minute: 150
      compliance-validation-enabled: true
      audit-logging-enabled: true
      security-monitoring-enabled: true
      performance-monitoring-enabled: true
      performance-warning-threshold-ms: 75
      performance-critical-threshold-ms: 150
      alert-notifications-enabled: true
      trusted-origins:
        - "https://demo.mambogo.com"
        - "http://localhost:5173"  # For development against demo backend

  # CSP Policy Configuration for Demo Environment
  csp:
    enabled: true
    report-only: false
    violation-reporting-enabled: true
    report-uri: "/api/csp/violations"
    max-violations-per-origin: 200  # Moderate limit for demo
    nonce-enabled: true
    hash-enabled: false  # Disabled for demo flexibility
    metrics-enabled: true
    performance-monitoring-enabled: true
    
    directives:
      default-src:
        - "'self'"
      script-src:
        - "'self'"
        - "'unsafe-inline'"  # Some flexibility for demo
        - "https://demo.mambogo.com"
      style-src:
        - "'self'"
        - "'unsafe-inline'"  # Flexibility for demo styling
        - "fonts.googleapis.com"
        - "https://demo.mambogo.com"
      img-src:
        - "'self'"
        - "data:"
        - "https:"
        - "https://demo.mambogo.com"
      connect-src:
        - "'self'"
        - "https://demo.mambogo.com"
        - "http://localhost:5173"  # For local development
      font-src:
        - "'self'"
        - "fonts.gstatic.com"
        - "fonts.googleapis.com"
        - "data:"
      object-src:
        - "'none'"
      media-src:
        - "'self'"
        - "https://demo.mambogo.com"
      child-src:
        - "'self'"
      frame-src:
        - "'self'"
      frame-ancestors:
        - "'none'"
      form-action:
        - "'self'"
        - "https://demo.mambogo.com"
      base-uri:
        - "'self'"
      manifest-src:
        - "'self'"
      worker-src:
        - "'self'"
      upgrade-insecure-requests: true  # Enforce HTTPS in demo
      block-all-mixed-content: false  # More lenient for demo