apiVersion: v1
kind: ConfigMap
metadata:
  name: mambogo-prod-config
  namespace: mambogo-prod
data:
  # Service URLs (Kubernetes-native)
  payment-service-url: "http://payment-service"
  product-service-url: "http://product-service"
  cart-service-url: "http://cart-service"
  
  # Infrastructure
  kafka-bootstrap-servers: "kafka-service:9092"
  eureka-server-url: "http://eureka-server:8761"
  
  # Database Configuration
  database-url: "jdbc:postgresql://orders-db:5432/orders"
  database-username: "postgres"
  database-password: "postgres"
  
  # Kafka Topics
  order-topic: "order-events"
  payment-topic: "payment-events"
  payment-dlq: "payment-events.DLQ"
  
  # Security
  keycloak-issuer: "http://keycloak:8080/realms/ecommerce"
  
  # Monitoring
  zipkin-endpoint: "http://zipkin:9411/api/v2/spans"
  
  # Application Settings
  spring-profiles-active: "prod"
  outbox-enabled: "true"
  outbox-poll-interval-ms: "1000"
  outbox-batch-size: "100"
  
  # CORS Configuration for Production Environment
  cors-enabled: "true"
  cors-allowed-origins: "https://www.mambogo.com,https://mambogo.com"
  cors-allow-credentials: "true"
  cors-max-age: "7200"
  
  # Advanced CORS Policy Configuration for Production
  cors-policy-enforcement-enabled: "true"
  cors-policy-auto-block-enabled: "true"
  cors-policy-auto-block-threshold: "10"
  cors-policy-auto-block-duration-hours: "48"
  cors-policy-require-user-agent: "true"
  cors-policy-max-requests-per-minute: "100"
  cors-policy-compliance-validation-enabled: "true"
  cors-policy-compliance-check-interval-hours: "12"
  cors-policy-security-monitoring-enabled: "true"
  cors-policy-security-analysis-interval-minutes: "3"
  cors-policy-performance-monitoring-enabled: "true"
  cors-policy-performance-warning-threshold-ms: "50"
  cors-policy-performance-critical-threshold-ms: "100"
  cors-policy-alert-notifications-enabled: "true"
  cors-policy-alert-suppression-interval-minutes: "5"
  cors-policy-incident-escalation-threshold: "3"