apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  labels:
    app: payment-service
    tier: backend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
        tier: backend
    spec:
      serviceAccountName: mambogo-service-account
      containers:
      - name: payment-service
        image: mambogo/payment-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: mambogo-config
              key: spring-profiles-active
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: mambogo-config
              key: kafka-bootstrap-servers
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: mambogo-config
              key: database-url
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: password
        - name: ORDER_TOPIC
          valueFrom:
            configMapKeyRef:
              name: mambogo-config
              key: order-topic
        - name: PAYMENT_TOPIC
          valueFrom:
            configMapKeyRef:
              name: mambogo-config
              key: payment-topic
        - name: PAYMENT_DLQ
          valueFrom:
            configMapKeyRef:
              name: mambogo-config
              key: payment-dlq
        - name: KC_ISSUER
          valueFrom:
            configMapKeyRef:
              name: mambogo-config
              key: keycloak-issuer
        - name: ZIPKIN_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: mambogo-config
              key: zipkin-endpoint
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8085
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8085
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: mambogo-config
