apiVersion: v1
kind: Service
metadata:
  name: cart-service
  labels:
    app: cart-service
    tier: backend
spec:
  selector:
    app: cart-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      name: http
  type: ClusterIP
