apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    app: gateway-service
    tier: frontend
spec:
  selector:
    app: gateway-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
  type: LoadBalancer  # For external access
