apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    app: kafka
    tier: infrastructure
spec:
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
      name: kafka
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  labels:
    app: zookeeper
    tier: infrastructure
spec:
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
      name: zookeeper
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: orders-db
  labels:
    app: postgres
    database: orders
    tier: infrastructure
spec:
  selector:
    app: postgres
    database: orders
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      name: postgresql
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: payments-db
  labels:
    app: postgres
    database: payments
    tier: infrastructure
spec:
  selector:
    app: postgres
    database: payments
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      name: postgresql
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: products-db
  labels:
    app: postgres
    database: products
    tier: infrastructure
spec:
  selector:
    app: postgres
    database: products
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      name: postgresql
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: cart-db
  labels:
    app: postgres
    database: cart
    tier: infrastructure
spec:
  selector:
    app: postgres
    database: cart
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      name: postgresql
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  labels:
    app: eureka-server
    tier: infrastructure
spec:
  selector:
    app: eureka-server
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
      name: http
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
    tier: infrastructure
spec:
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
  labels:
    app: zipkin
    tier: infrastructure
spec:
  selector:
    app: zipkin
  ports:
    - protocol: TCP
      port: 9411
      targetPort: 9411
      name: http
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    tier: infrastructure
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      name: redis
  type: ClusterIP
