apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
    tier: backend
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
      name: http
  type: ClusterIP
