apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    app: payment-service
    tier: backend
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
      name: http
  type: ClusterIP
