apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product-service
    tier: backend
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      name: http
  type: ClusterIP
